### PR TITLE
Adding Export of Stack Output values

### PR DESCRIPTION
**Pull request by RobBiddle**
*Description of changes:*

Adding Export of Stack Output values.  This allows for integrating this template into deployments which make use of cross-stack references. 

This is something I need for the deployments I manage and I suspect I'm not the only one who will appreciate this simple change.

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by ericquinones** [comment]
Thank you for the contribution @RobBiddle. We are going to evaluate including this in a future release of the solution.

**Comment by aijunpeng** [comment]
Thanks for your contribution! It is added to our backlog and will be evaluated in a future release.

**Comment by matthewhembree** [comment]
This is a simple passive change that adds great convenience, can we get this promoted? This is >2yrs old.

**Comment by aijunpeng** [comment]
Thanks for your comment. We will bring this to the top of our road map and re-evaluate it.

**Comment by aijunpeng** [comment]
This change has been included in v4.0.0.

**Pull request closed without merging**
